# Generated by Django 2.2.3 on 2019-07-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pari', '0002_tiquet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tiquet',
            old_name='auteur',
            new_name='joueur',
        ),
        migrations.AlterField(
            model_name='tiquet',
            name='mise',
            field=models.IntegerField(max_length=150),
        ),
        migrations.AlterField(
            model_name='tiquet',
            name='numero1',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='tiquet',
            name='numero2',
            field=models.IntegerField(max_length=10),
        ),
    ]
