# Generated by Django 2.2.3 on 2019-07-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pari', '0003_auto_20190729_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiquet',
            name='mise',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tiquet',
            name='numero1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tiquet',
            name='numero2',
            field=models.IntegerField(),
        ),
    ]
