# Generated by Django 2.2.3 on 2019-07-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pari', '0006_tiquet_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lotterie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=150)),
                ('ouverture', models.DateTimeField()),
                ('fermeture', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='tiquet',
            name='event',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
