# Generated by Django 2.2.3 on 2019-07-29 16:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pari', '0007_auto_20190729_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotterie',
            name='fermeture',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='lotterie',
            name='ouverture',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
