# Generated by Django 2.2.3 on 2019-07-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pari', '0008_auto_20190729_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotterie',
            name='description',
            field=models.TextField(default='Entrer la description Ici'),
        ),
    ]
