# Generated by Django 2.2.3 on 2019-07-30 11:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pari', '0010_auto_20190729_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(default='Entrer la description Ici')),
                ('ouverture', models.DateTimeField(default=django.utils.timezone.now)),
                ('fermeture', models.DateTimeField(default=django.utils.timezone.now)),
                ('numero_gagnat', models.CharField(blank=True, max_length=150)),
            ],
        ),
    ]
